INSERT INTO TODO (TEXT, STATUS) VALUES ('Learn Java', FALSE);
INSERT INTO TODO (TEXT, STATUS) VALUES ('Learn Python', FALSE);
INSERT INTO TODO (TEXT, STATUS) VALUES ('Learn JavaScript', FALSE);
INSERT INTO TODO (TEXT, STATUS) VALUES ('Learn Spring Framework', FALSE);
INSERT INTO TODO (TEXT, STATUS) VALUES ('Learn PHP', FALSE);
INSERT INTO TODO (TEXT, STATUS) VALUES ('Learn Laravel', FALSE);
INSERT INTO TODO (TEXT, STATUS) VALUES ('Learn Visual Basic', FALSE);
INSERT INTO TODO (TEXT, STATUS) VALUES ('Learn C++', FALSE);